//! `docs/cli.md`: a Markdown reference generated from the clap tree
//! (`stems __docs`, `make docs`), golden-tested in `tests/docs.rs`.

use clap::Command;

/// The whole reference.
pub fn markdown() -> String {
    let mut out = String::from(
        "# stems command-line reference\n\n\
         <!-- Generated by `make docs` (`stems __docs`) from the clap definitions in\n\
         crates/stems-cli/src/cli.rs. Do not edit by hand: crates/stems-cli/tests/docs.rs\n\
         fails when this file drifts; `UPDATE_DOCS=1 cargo test -p stems-cli --test docs`\n\
         rewrites it. -->\n\n\
         Every command accepts the global flags shown under `stems`. Output is\n\
         human text on a terminal and the JSON envelope\n\
         `{ \"ok\": bool, \"data\": ..., \"errors\": [...], \"version\": \"x.y.z\" }`\n\
         when stdout is not a terminal or with `--json` (`--human` forces text).\n\
         Exit codes: 0 ok, 1 runtime failure, 2 config/validation/usage error,\n\
         3 partial success or orphans, 4 daemon unavailable. Commands whose\n\
         deliverable has not landed yet return `NOT_IMPLEMENTED` (exit 1).\n\n\
         **Exception:** `stems events --json` prints NDJSON, one event object per\n\
         line (`{ts, seq, kind, stem, from, to, reason, actor, data}`) and no\n\
         envelope, so external automation can consume `stems events -f --json`\n\
         line by line (FR-CL-4); errors (e.g. exit 4 `DAEMON_NOT_RUNNING`) still\n\
         print the envelope. The daemon's wire protocol is documented in\n\
         `docs/protocol.md`.\n",
    );
    for (path, help) in visible_commands() {
        let level = if path == "stems" { "##" } else { "###" };
        out.push_str(&format!(
            "\n{level} `{path}`\n\n```text\n{}\n```\n",
            help.trim_end()
        ));
    }
    out
}

/// Every visible command path with its long help, depth first.
pub fn visible_commands() -> Vec<(String, String)> {
    let mut cmd = crate::cli::command();
    let mut v = Vec::new();
    collect(&mut cmd, "stems", &mut v);
    v
}

fn collect(cmd: &mut Command, path: &str, out: &mut Vec<(String, String)>) {
    out.push((path.to_string(), cmd.render_long_help().to_string()));
    let names: Vec<String> = cmd
        .get_subcommands()
        .filter(|s| !s.is_hide_set() && s.get_name() != "help")
        .map(|s| s.get_name().to_string())
        .collect();
    for n in names {
        if let Some(sub) = cmd.find_subcommand_mut(&n) {
            collect(sub, &format!("{path} {n}"), out);
        }
    }
}
